version: "3"
services:
  unifi-api-browser:
    build: .
    image: unifi-api-browser
    container_name: unifi-api-browser
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /config.php:/app/config.php:ro
      
      
